<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <UseMicrosoftTestingPlatformRunner>true</UseMicrosoftTestingPlatformRunner>
    <TestingPlatformDotnetTestSupport>true</TestingPlatformDotnetTestSupport>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\IkuyoPet.Core\IkuyoPet.Core.csproj" />
    <ProjectReference Include="..\..\src\IkuyoPet.Infrastructure\IkuyoPet.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\IkuyoPet.Pet\IkuyoPet.Pet.csproj" />
    <PackageReference Include="xunit.v3" />
  </ItemGroup>
</Project>