<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\IkuyoPet.Core\IkuyoPet.Core.csproj" />
    <ProjectReference Include="..\..\src\IkuyoPet.Infrastructure\IkuyoPet.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\IkuyoPet.Pet\IkuyoPet.Pet.csproj" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="xunit.runner.visualstudio" PrivateAssets="all" />
    <PackageReference Include="coverlet.collector" PrivateAssets="all" />
  </ItemGroup>
</Project>
