<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <RootNamespace>IkuyoPet.Infrastructure</RootNamespace>
    <AssemblyName>IkuyoPet.Infrastructure</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\IkuyoPet.Core\IkuyoPet.Core.csproj" />
    <PackageReference Include="Microsoft.Data.Sqlite" />
    <PackageReference Include="Microsoft.WindowsAppSDK" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="IkuyoPet.Infrastructure.Tests" />
  </ItemGroup>
</Project>
